title: minh trieu t., dl researcher
url: "https://trgmtr.github.io"
baseurl: "/trieutrg"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/trgmtr"
footer_text: "2026 by minh trieu t."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: "https://ankitsultana.com/researcher/"
